<?php
// echo "<pre>";
// print_r($weatherresult);

?>

<div class="container-fluid mt-1 mb-3">
    <div class="row justify-content-center">
        <div class="card col-md-8 " style="color: #4B515D; border-radius: 35px;">
          <div class="card-body p-4">

            <div class="d-flex">
              <h6 class="flex-grow-1 text-danger"><?php echo $weatherresult['location']['name']; ?></h6>
              <h6 class="text-primary" ><?php echo $weatherresult['location']['localtime']; ?></h6>
            </div>

            <div class="d-flex flex-column text-center mt-5 mb-4">
              <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"><?php echo $weatherresult['current']['temp_c']; ?>°C</h6>
              <span class="small" style="color: #868B94"><?php echo $weatherresult['current']['condition']['text']; ?></span>
            </div>

            <div class="d-flex align-items-center">
              <div class="flex-grow-1" style="font-size: 1rem;">
                <div><i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1"> <?php echo $weatherresult['current']['wind_kph']; ?>km/h </span></div>
                <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1"> <?php echo $weatherresult['current']['humidity']; ?> </span></div>
                <div><i class="fas fa fa-fw" style="color: #868B94;">D</i> <span class="ms-1"><?php echo $weatherresult['current']['wind_dir']; ?> </span></div>
              </div>
              <div>
                <img src="<?php echo $weatherresult['current']['condition']['icon']; ?>" width="100px">
              </div>
            </div>

          </div>
        </div>
        
    </div>
</div>



<?php 
?>