<?php

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../../../public/assets/style.css">
</head>
<body>
<div class="main-search-input-wrap">
     <div class="main-search-input fl-wrap">
<form action="getlocation/getCurrent"><div class="main-search-input-item"><input type="text"  placeholder="Search Location" name="location" > </div> <button class="main-search-button"  >Search</button></form>
     </div>
 </div>
</body>
</html>