<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#e2dcc5">
    <title>Document</title>

    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<style>.card-horizontal {
    display: flex;
    flex: 1 1 auto;
}
html{
    color: #e2dcc5;
}</style>
<body>
    <?php $weatherresult = $this->session->get('result'); ?> 
   <div class="container">
   <section class="" style="background-color: #4B515D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-75">
    <div class="text-center" >
    <a class="btn text-white" href="../getlocation/getCurrent?location=<?php echo $weatherresult['location']['name']; ?>" >Current</a>
          <a class="btn text-white" href="../getlocation/getForecast?location=<?php echo $weatherresult['location']['name']; ?>" >Forecast(today)</a>
          <a class="btn text-white"  href="../getlocation/getHistory?date=<?php 
          $string =  $weatherresult['location']['localtime'];
          $output = strtok($string,  ' ');
          echo $output; 
          ?>&location=<?php echo $weatherresult['location']['name']; ?>" >History</a>
          
          <a class="btn text-white"  href="../getlocation/getSports?location=<?php echo $weatherresult['location']['name']; ?>" >Sports</a>
          <a class="btn text-white" href="../getlocation/getAstronomy?date=<?php 
          $string =  $weatherresult['location']['localtime'];
          $output = strtok($string,  ' ');
          echo $output; 
          ?>&location=<?php echo $weatherresult['location']['name']; ?>" >Astronomy</a>
          <a class="btn text-white" href="../getlocation/getAlert?location=<?php echo $weatherresult['location']['name']; ?>" >Weather Alerts</a>
          <a class="btn text-white" href="../getlocation/getAqi?location=<?php echo $weatherresult['location']['name']; ?>" >Air Quality</a>
          <a class="btn text-white" href="../getlocation/getTimezone?location=<?php echo $weatherresult['location']['name']; ?>" >TimeZone</a>
          <a class="btn text-white" href="/" >Search</a>
    </div>
      <div class="">

      <?php echo $this->getContent(); ?>

      </div>
    </div>
</div>
</section>
   </div>
</body>
</html>